name: Deploy Dev App

on:
  push:
    paths:
      - 'app/Program.cs'
    branches:
      - dev

permissions:
  contents: read
  id-token: write      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.100

      - name: Restore dependencies
        run: dotnet restore

      - name: Build application
        run: dotnet build --configuration Release --no-restore

      - name: Publish application
        run: dotnet publish -c Release -o ./publish

      - name: Create zip archive
        run: zip -r app.zip publish

      - name: Assume AWS IAM Role
        id: assume-role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: 'arn:aws:iam::637423392537:role/GithubActions'
          role-session-name: github-actions
          aws-region: 'us-east-1'

      - name: Build application (Release configuration)
        run: dotnet build --configuration Release

      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk update-environment \
            --application-name isaac-beanstalk-dev-DotNetApp \
            --environment-name ${{ env.EB_ENV_NAME }} \
            --source-bundle fileb://./publish/app.zip \
            --version-label V${{ env.APP_VERSION }} \
            --region us-east-1
        env:
          EB_ENV_NAME: isaac-beanstalk-dev-DotNetEnvironment
          APP_VERSION: 1.0.0