name: Deploy Dev App

on:
  push:
    paths:
      - 'app/Program.cs'
    branches:
      - dev

permissions:
  contents: read
<<<<<<< HEAD
  id-token: write
=======
  id-token: write      
>>>>>>> 681382554b151956172c9bf810b1d79dce7d44c1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: 'arn:aws:iam::637423392537:role/GithubActions'
          role-session-name: github-actions

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.100

      - name: Restore dependencies
        run: dotnet restore

      - name: Build application
        run: dotnet build --configuration Release --no-restore

      - name: Publish application
        run: dotnet publish -c Release -o ./publish

      - name: Create zip archive
        run: zip -r app.zip publish

      - name: Build application (Release configuration)
        run: dotnet build --configuration Release

      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version \
<<<<<<< HEAD
            --application-name isaac-beanstalk-prod-DotNetApp \
=======
            --application-name isaac-beanstalk-dev-DotNetApp \
>>>>>>> 681382554b151956172c9bf810b1d79dce7d44c1
            --version-label V${{ env.APP_VERSION }} \
            --source-bundle fileb://./app.zip \
            --region us-east-1      

          aws elasticbeanstalk update-environment \
            --application-name isaac-beanstalk-dev-DotNetApp \
            --environment-name ${{ env.EB_ENV_NAME }} \
            --version-label V${{ env.APP_VERSION }} \
            --region us-east-1
        env:
<<<<<<< HEAD
          EB_ENV_NAME: isaac-beanstalk-prod-DotNetEnvironment
=======
          EB_ENV_NAME: isaac-beanstalk-dev-DotNetEnvironment
>>>>>>> 681382554b151956172c9bf810b1d79dce7d44c1
          APP_VERSION: 1.0.0