name: Deploy to App to Prod EB Environment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults: 
      run: 
        working-directory: app

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.100'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Publish
      run: dotnet publish --configuration Release --output ./publish

    - name: Configure AWS credentials
      id: configure-aws-credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::730335212900:role/GithubActions
        role-session-name: github-actions
        aws-region: us-east-1

    - name: Zip published application
      run: zip -r app.zip ./publish

    - name: Upload to S3
      run: aws s3 cp app.zip s3://isaac-beanstalk-prod-bucket/app.zip

    - name: Create new application version
      run: aws elasticbeanstalk create-application-version --application-name isaac-beanstalk-prod-DotNetApp --version-label $GITHUB_SHA --source-bundle S3Bucket=isaac-beanstalk-prod-bucket,S3Key=app.zip

    - name: Update Elastic Beanstalk environment
      run: aws elasticbeanstalk update-environment --environment-name isaac-beanstalk-prod-DotNetEnvironment --version-label $GITHUB_SHA